pipeline {
    agent any
        stages {
            stage('Build') {
                steps {
                    sh 'cd gs-gradle"'
                    sh ' gradle'
                }
            }
            stage('Test') {
                steps {
                    sh 'echo "Hello World"'
                    sh '''
                        echo "Multiline shell steps works too"
                        ls -lah
                    '''
                }
            }
    }
}