CREATE TABLE produto (
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    preco DECIMAL(6) NOT NULL, 
    quantidade INT NOT NULL
    ) 
    ENGINE=InnoDB DEFAULT CHARSET=UTF8;